name: Backwards Compatibility Check
on: [pull_request]
jobs:
  # More info at https://github.com/Roave/BackwardCompatibilityCheck.
  backwards-compatibility-check:
    runs-on: ubuntu-latest
    # Disable this check by applying the 'breaking change allowed' label to the PR.
    if: "!contains(github.event.pull_request.labels.*.name, 'breaking change allowed')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install roave BC checker
        run: composer global require roave/backward-compatibility-check
      - name: Check for BC breaks
        run: |
          export PATH=$PATH:~/.composer/vendor/bin
          roave-backward-compatibility-check
